version: "3"

services:
  fc_wallet_ms:
    #image: golang:1.20
    build: .
    container_name: fc_wallet_ms
    platform: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - .:/app
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql